# fly.toml app configuration file generated for brain-ball on 2023-08-22T03:21:16+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "brain-ball"
primary_region = "cdg"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
